### ISSUE TITLE
Add section on HHS-HCC risk adjustment

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/docs#160]

**Comment by chase-jones** [comment]
@aneiderhiser , I can give a go of this one next if you'd like. I'll be stepping a little outside my comfort zone with this one, but hopefully get it at a high level. May reshape the risk adjustment section a little

**Comment by aneiderhiser** [comment]
@chase-jones sounds great!

**Comment by EeethB** [comment]
Hey Tuva folks! I'm just starting on an issue for the implementation of this model on the main repo: https://github.com/tuva-health/the_tuva_project/issues/276

Is this issue related to implementation or only docs? I will wait to work on it if it's already started.

**Comment by chase-jones** [comment]
@EeethB for this issue, I think it's only specific to the docs (at least, that's the only thing I'll be working on for this issue).

**Comment by aneiderhiser** [comment]
Yeah these are separate - this one is docs (knowledge base) and @EeethB's is the data mart.  The initial docs @chase-jones is working on is a general description of HHS-HCCs.  Once the mart is released we'll want to update the docs to include "here's how you can use / analyze HHS-HCCs using the data mart".  

Super excited to see this come together!
