### ISSUE TITLE
Bug: Readmissions Data Quality Example SQL Missing Column

### ISSUE THREAD

**Issue by cnolanminich** [tuva-health/docs#183]
**Is your feature request related to a problem? Please describe.**
When you try to query the example SQL for readmission data quality issues, it fails because it cannot find a column `multiple_primary_diagnoses_flag` in `readmissions.encounter_augmented`. I double checked that table and didn't see any similarly named column.

https://github.com/tuva-health/knowledge_base/blob/main/docs/tuva-data/example-sql.md#readmissions

**Describe the solution you'd like**
Remove the column or rename to the appropriate column

**Describe alternatives you've considered**

Leave the SQL with a syntax error.

**Additional context**

**Comment by cocozuloaga** [comment]
Docs has been refactored and readmission analytics examples are now up to date and corrected and under the Readmissions data mart, so this issue is not relevant anymore.
