### ISSUE TITLE
ED classification needs column documentation

### ISSUE THREAD

**Issue by tuvaforrest** [tuva-health/docs#207]
I don't know if the issue should go here or in the tuva project, but the [ED classification ](https://thetuvaproject.com/data-dictionaries/ed-classification) data dictionary is missing most of its info.  There is an [entry for the model](https://github.com/tuva-health/the_tuva_project/blob/main/models/ed_classification/ed_classification_models.yml) in the correct place in the yaml, but the columns in the yaml are almost entirely different than the [columns in the actual model](https://github.com/tuva-health/the_tuva_project/blob/main/models/ed_classification/final/ed_classification__summary.sql), so we end up with capital column names and no descriptions.

**Comment by sarah-tuva** [comment]
Resoved in [#336](https://github.com/tuva-health/tuva/pull/336)
