### ISSUE TITLE
Add CMS HCC mart to Guides

### ISSUE THREAD

**Issue by sarah-tuva** [tuva-health/docs#231]
**Is your feature request related to a problem? Please describe.**
It's difficult to find the guide on using the mart on the [CMS HCC](https://thetuvaproject.com/knowledge-base/risk-adjustment/cms-hccs) page under Knowledge Base.

**Describe the solution you'd like**
It would be nice to have a separate guide for how to use this data mart.  This would include:

1. Overview of main use cases for running this mart (e.g. you want to prospectively estimate HCC risk scores for your patient population)
2. Describe how to run it (i.e. dbt + tuva instructions)
3. Describe how to analyze the tables

**Comment by aneiderhiser** [comment]
The Knowledge Base page should remain, but we should remove duplicate content from it that will now be in this guide.  The type of content that remains should be more general content (e.g. what are MMR / MOR files).

**Comment by aneiderhiser** [comment]
@sarah-tuva see geospatial guide for example.
