### ISSUE TITLE
Update data models

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/docs#44]
Review all data models to make sure they reflect reality.

Encounter table needs admission and discharge dates.

**Comment by cocozuloaga** [comment]
Specific to encounter table:
- We decided it does NOT need admission and discharge dates
- We need to remove the 'physician_npi' field and add 'rendering_npi', 'billing_npi', 'facility_npi' fields
- We need to add 'ms_drg_description' field
- We need to add 'paid_date' field
- We need to add 'allowed_amount' field

**Comment by aneiderhiser** [comment]
@cocozuloaga are these changes that need to be made to the code/repo?  I have updated these changes in KB - they aren't in production yet (i.e. not all thetuvaproject.com yet) but will be when I released KB next.

**Comment by cocozuloaga** [comment]
@aneiderhiser , ok great! They are changes that need to be made in KB so that they are reflected in thetuvaproject.com.
